import { beforeEach, describe, expect, it } from "vitest";
import { scenarios, getScenario } from "@/content/scenarios";
import { issueRecoveryCode, issueSession, parseRecoveryCode } from "@/server/auth/crypto";
import { MemoryStore, resetMemoryStoreForTests } from "./memory";

function identity(store: MemoryStore, name = "Alex") {
  const now = new Date("2026-01-01T00:00:00.000Z"); const session = issueSession(now); const recovery = issueRecoveryCode();
  return store.createIdentity({ displayName: name, contactEmail: `${name.toLowerCase()}@example.com`, session: { tokenHash: session.tokenHash, expiresAt: session.expiresAt }, recovery: { lookupId: recovery.lookupId, secretHash: recovery.secretHash }, now }).then(user => ({ user, session, recovery, now }));
}

describe("cloud save service", () => {
  let store: MemoryStore;
  beforeEach(async()=>{resetMemoryStoreForTests();store=new MemoryStore();await store.syncScenarios(scenarios)});
  it("enforces ownership, idempotency, and optimistic versioning", async()=>{
    const a=await identity(store,"Alex");const b=await identity(store,"Blair");const scenario=getScenario("ai-workflow-automation")!;
    const run=await store.createRun(a.user.id,scenario,{companyName:"Orbit",founderArchetype:"builder",difficulty:"realistic",personalRunway:"standard"},123,a.now);
    expect(await store.getRun(b.user.id,run.id)).toBeNull();
    const request={commandId:"fixed-command-1",expectedVersion:1,type:"problem.hypothesis.set" as const,payload:{problemId:"problem_1",hypothesisId:"problem_1_hypothesis_1"}};
    const first=await store.executeCommand(a.user.id,run.id,request,new Date("2026-01-01T00:00:01Z"));
    const duplicate=await store.executeCommand(a.user.id,run.id,request,new Date("2026-01-01T00:00:02Z"));
    expect(duplicate.version).toBe(first.version);expect(duplicate.checksum).toBe(first.checksum);expect("hidden" in first.state).toBe(false);
    await expect(store.executeCommand(a.user.id,run.id,{...request,commandId:"new-command",expectedVersion:1},new Date())).rejects.toThrow("VERSION_CONFLICT");
  });
  it("creates immutable checkpoint forks",async()=>{const a=await identity(store);const scenario=getScenario("local-services-saas")!;const run=await store.createRun(a.user.id,scenario,{companyName:"LocalCo",founderArchetype:"seller",difficulty:"realistic",personalRunway:"pressure"},9,a.now);const checkpoint=await store.createCheckpoint(a.user.id,run.id,"Before first decision",a.now);const fork=await store.forkRun(a.user.id,run.id,checkpoint.id,a.now);expect(fork.parentRunId).toBe(run.id);expect(fork.id).not.toBe(run.id);expect(fork.state.meta.companyName).toBe(run.state.meta.companyName)});
  it("consumes a recovery code, revokes prior sessions, and rotates the credential",async()=>{const account=await identity(store);const parsed=parseRecoveryCode(account.recovery.code)!;const nextSession=issueSession(account.now);const next=issueRecoveryCode();const user=await store.recoverIdentity({...parsed,session:{tokenHash:nextSession.tokenHash,expiresAt:nextSession.expiresAt},replacement:{lookupId:next.lookupId,secretHash:next.secretHash},now:account.now});expect(user.id).toBe(account.user.id);expect(await store.resolveSession(account.session.tokenHash,account.now)).toBeNull();await expect(store.recoverIdentity({...parsed,session:{tokenHash:"x",expiresAt:nextSession.expiresAt},replacement:{lookupId:"y",secretHash:"z"},now:account.now})).rejects.toThrow("INVALID_RECOVERY_CODE")});
  it("rotates a session only after the seven-day threshold",async()=>{const account=await identity(store);const early=issueSession(new Date("2026-01-02"));expect(await store.refreshSession(account.user.id,account.session.tokenHash,{tokenHash:early.tokenHash,expiresAt:early.expiresAt},new Date("2026-01-02"))).toBe(false);const lateNow=new Date("2026-01-09");const late=issueSession(lateNow);expect(await store.refreshSession(account.user.id,account.session.tokenHash,{tokenHash:late.tokenHash,expiresAt:late.expiresAt},lateNow)).toBe(true);expect(await store.resolveSession(account.session.tokenHash,lateNow)).toBeNull();expect((await store.resolveSession(late.tokenHash,lateNow))?.id).toBe(account.user.id)});
  it("persists an allowlisted competitor decision as an idempotent external input",async()=>{const a=await identity(store);const scenario=getScenario("ai-workflow-automation")!;let run=await store.createRun(a.user.id,scenario,{companyName:"WorldCo",founderArchetype:"builder",difficulty:"realistic",personalRunway:"standard"},71,a.now);let counter=0;while(!run.state.features?.public.competitors?.pendingTurn&&counter<12){const type=run.state.pendingEvent?"event.respond" as const:"operations.advance_to_decision" as const;const payload=run.state.pendingEvent?{choiceIndex:0}:{maxDays:14};await store.executeCommand(a.user.id,run.id,{commandId:`world-command-${counter++}`,expectedVersion:run.stateVersion,type,payload},new Date(`2026-01-${String(Math.min(28,counter+1)).padStart(2,"0")}T00:00:00Z`));run=(await store.getRun(a.user.id,run.id))!;}expect(run.state.features?.public.competitors?.pendingTurn).toBeTruthy();const [first,duplicate]=await Promise.all([store.resolvePendingAgentTurn(a.user.id,run.id,new Date("2026-02-01T00:00:00Z")),store.resolvePendingAgentTurn(a.user.id,run.id,new Date("2026-02-01T00:00:01Z"))]);expect(first?.status).toBe("completed");expect(duplicate?.status).toBe("completed");expect(await store.resolvePendingAgentTurn(a.user.id,run.id,new Date("2026-02-01T00:00:02Z"))).toBeNull();const inputs=await store.listExternalInputs(a.user.id,run.id);expect(inputs.map((item)=>item.kind)).toEqual(["market_dossier","agent_decision"]);expect((await store.getRun(a.user.id,run.id))?.state.features?.public.competitors?.moves).toHaveLength(1)});
});
