import Link from "next/link";
import { ArrowRight, CircleDollarSign, Gauge, History, Plus, Users } from "lucide-react";
import { redirect } from "next/navigation";
import type { FinanceTreasuryPublicStateV10, FounderManagementPublicStateV10, WorkforcePublicStateV10 } from "@sim/engine";
import { LegacyImport } from "@/components/legacy-import";
import { currentUser } from "@/server/auth/session";
import { getStore } from "@/server/store";
import { money, number, relativeTime } from "@/lib/ui";
import { projectRun, projectV10Run } from "@/server/store/projection";
import type { ClientRunRecord, ClientV10RunRecord } from "@/server/store/types";

export const metadata={title:"Dashboard"};
export const dynamic="force-dynamic";

function isV10Run(run:ClientRunRecord|ClientV10RunRecord):run is ClientV10RunRecord{return "stateFormat" in run;}

export default async function DashboardPage(){
  const user=await currentUser();if(!user)redirect("/start");const store=await getStore();
  const legacy=(await store.listRuns(user.id)).map(projectRun);const v10=(await store.listV10Runs(user.id)).map(projectV10Run);
  const runs:Array<ClientRunRecord|ClientV10RunRecord>=[...legacy,...v10];runs.sort((a,b)=>b.lastPlayedAt.localeCompare(a.lastPlayedAt));const latest=runs.find((run)=>run.status==="active");
  const latestV10=latest&&isV10Run(latest)?latest:null;const latestLegacy=latest&&!isV10Run(latest)?latest:null;
  const workforce=latestV10?.state.features["workforce-and-organization"] as WorkforcePublicStateV10|undefined;
  const finance=latestV10?.state.features["finance-and-treasury"] as FinanceTreasuryPublicStateV10|undefined;
  const management=latestV10?.state.features["founder-and-management"] as FounderManagementPublicStateV10|undefined;
  return <div className="container-page py-8 sm:py-10"><header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="eyebrow">Founder command center</div><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-4xl">Welcome back, {user.displayName}.</h1><p className="muted mt-2">Continue from the latest accepted cloud command.</p></div><Link href="/scenarios" className="btn btn-primary"><Plus size={16}/>New run</Link></header>
  {latest?<section className="surface mt-8 overflow-hidden p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className="pill pill-good">Continue run</span><span className="pill">Day {latestV10?latestV10.state.kernel.simulationDay:latestLegacy!.state.calendar.absoluteDay}</span><span className="pill">{latestV10?"V10 workforce actors":latestLegacy!.state.meta.vertical}</span></div><h2 className="mt-4 text-2xl font-black">{latest.title}</h2><p className="muted mt-1 text-sm">Saved {relativeTime(latest.lastPlayedAt)} · state v{latest.stateVersion} · {latest.checksum.slice(0,8)}</p></div><Link className="btn btn-primary" href={`/runs/${latest.id}`}>Continue decision path <ArrowRight size={16}/></Link></div>
  {latestV10?<div className="metric-grid mt-6"><div className="metric-card"><CircleDollarSign className="text-emerald-300" size={17}/><div className="metric-label mt-3">Company cash</div><div className="metric-value">{money(finance?.cash??0)}</div><div className="metric-note">Payable {money(finance?.peoplePayable??0)}</div></div><div className="metric-card"><Users className="text-sky-300" size={17}/><div className="metric-label mt-3">Workforce</div><div className="metric-value">{workforce?.employees.filter((item)=>item.status!=="departed").length??1}/25</div><div className="metric-note">{workforce?.openRoles.filter((item)=>item.status==="open").length??0} openings</div></div><div className="metric-card"><Gauge className="text-amber-300" size={17}/><div className="metric-label mt-3">Management</div><div className="metric-value capitalize">{management?.managementSignal??"controlled"}</div><div className="metric-note">{management?.committedHours.toFixed(1)??"0"} committed hours</div></div><div className="metric-card"><History className="text-amber-300" size={17}/><div className="metric-label mt-3">Timeline</div><div className="metric-value">{latest.headEventSequence}</div><div className="metric-note">Immutable events</div></div></div>:<div className="metric-grid mt-6"><div className="metric-card"><CircleDollarSign className="text-emerald-300" size={17}/><div className="metric-label mt-3">Company cash</div><div className="metric-value">{money(latestLegacy!.state.finance.companyCash)}</div><div className="metric-note">MRR {money(latestLegacy!.state.finance.mrr)}</div></div><div className="metric-card"><Gauge className="text-sky-300" size={17}/><div className="metric-label mt-3">Founder load</div><div className="metric-value">{number(latestLegacy!.state.founder.burnout)}%</div><div className="metric-note">Energy {number(latestLegacy!.state.founder.energy)}%</div></div><div className="metric-card"><div className="text-emerald-300">◈</div><div className="metric-label mt-3">Evidence</div><div className="metric-value">{number(latestLegacy!.state.evidence.problem)}/100</div><div className="metric-note">Budget {number(latestLegacy!.state.evidence.budget)}/100</div></div><div className="metric-card"><History className="text-amber-300" size={17}/><div className="metric-label mt-3">Timeline</div><div className="metric-value">{latest.headEventSequence}</div><div className="metric-note">Immutable events</div></div></div>}</section>:<section className="surface mt-8 p-8 text-center"><div className="eyebrow">No active runs</div><h2 className="mt-3 text-2xl font-black">Your first startup starts with a constraint.</h2><p className="muted mx-auto mt-2 max-w-xl">Choose a scenario, configure the founder, and make the first decision.</p><Link href="/scenarios" className="btn btn-primary mt-6">Choose a scenario <ArrowRight size={16}/></Link></section>}
  <section className="mt-8"><h2 className="text-xl font-black">All runs</h2><p className="muted mt-1 text-sm">V7–V9 JSON heads and V10 feature heads remain isolated replay paths.</p><div className="mt-4 grid gap-3">{runs.map((run)=>{const v10Run=isV10Run(run);return <Link key={run.id} href={`/runs/${run.id}`} className="surface-soft flex items-center justify-between gap-4 p-4 transition hover:border-emerald-300/30"><div className="min-w-0"><div className="truncate font-bold">{run.title}</div><div className="muted mt-1 text-xs">{v10Run?`V10 · Day ${run.state.kernel.simulationDay}`:`${run.state.meta.vertical} · Day ${run.state.calendar.absoluteDay}`} · {relativeTime(run.lastPlayedAt)}</div></div><div className="flex shrink-0 items-center gap-2"><span className="pill">{v10Run?"feature heads":"legacy head"}</span><span className={`pill ${run.status==="active"?"pill-good":"pill-bad"}`}>{run.status}</span><ArrowRight size={15}/></div></Link>})}</div></section><section className="mt-8"><LegacyImport/></section></div>;
}
