"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { GitFork, History, LoaderCircle, Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useMemo, useState } from "react";
import type { HistoryEvent } from "@sim/engine";
import type { CheckpointRecord } from "@/server/store/types";
import { cn } from "@/lib/ui";

const categories=["all","finance","evidence","customer","product","people","risk","capital","action","stakeholder","problem","system"];
export function HistoryView({runId,initialEvents,initialCheckpoints}:{runId:string;initialEvents:HistoryEvent[];initialCheckpoints:CheckpointRecord[]}){
  const router=useRouter();const [filter,setFilter]=useState("all");const [checkpoints,setCheckpoints]=useState(initialCheckpoints);const [name,setName]=useState("");const [pending,setPending]=useState(false);const [error,setError]=useState("");
  const events=useMemo(()=>filter==="all"?initialEvents:initialEvents.filter(event=>event.category===filter),[filter,initialEvents]);
  async function create(event:FormEvent){event.preventDefault();setPending(true);setError("");const response=await fetch(`/api/v1/runs/${runId}/checkpoints`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const body=await response.json();setPending(false);if(!response.ok){setError(body.error);return}setCheckpoints(current=>[body.checkpoint,...current]);setName("")}
  async function fork(checkpointId:string){setPending(true);setError("");const response=await fetch(`/api/v1/runs/${runId}/forks`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({checkpointId})});const body=await response.json();setPending(false);if(!response.ok){setError(body.error);return}router.push(`/runs/${body.run.id}`);router.refresh()}
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="surface p-4 sm:p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">Causal timeline</h2><p className="muted mt-1 text-xs">Append-only events. Filters never change the underlying run.</p></div><div className="flex max-w-full gap-1 overflow-x-auto">{categories.map(category=><button key={category} className={cn("pill capitalize",filter===category&&"pill-good")} onClick={()=>setFilter(category)}>{category}</button>)}</div></div><div className="relative mt-6 space-y-3 before:absolute before:bottom-3 before:left-[17px] before:top-3 before:w-px before:bg-slate-700">{events.length?events.map(event=><article className="relative pl-11" key={event.id}><div className={cn("absolute left-2.5 top-4 size-3 rounded-full border-2 border-[#0d1925]",event.category==="finance"?"bg-amber-300":event.category==="evidence"?"bg-sky-300":event.category==="problem"?"bg-red-400":"bg-emerald-300")}/><div className="surface-soft p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-sm font-bold">{event.summary}</div><div className="faint mt-1 text-xs">Day {event.simulationDay} · sequence {event.sequence} · {event.actor}</div></div><span className="pill capitalize">{event.category}</span></div>{event.effects.length>0&&<div className="mt-3 grid gap-1.5 sm:grid-cols-2">{event.effects.map(effect=><div className="rounded-lg bg-black/20 px-2.5 py-2 text-[11px]" key={`${event.id}:${effect.path}`}><span className="muted">{effect.path}</span><div className="mt-1 font-mono"><span className="text-red-200">{String(effect.before)}</span> → <span className="text-emerald-200">{String(effect.after)}</span></div></div>)}</div>}</div></article>):<div className="muted py-12 text-center">No events match this filter.</div>}</div></section>
  <aside className="space-y-4"><section className="surface p-5"><div className="flex items-center justify-between"><div><h2 className="font-black">Checkpoints</h2><p className="muted mt-1 text-xs">Forking preserves the original timeline.</p></div><Dialog.Root><Dialog.Trigger asChild><button className="btn btn-secondary !min-h-9 !px-3"><Plus size={15}/><span className="sr-only">Create checkpoint</span></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm"/><Dialog.Content className="surface fixed left-1/2 top-1/2 z-50 w-[min(92vw,440px)] -translate-x-1/2 -translate-y-1/2 p-6"><div className="flex items-start justify-between"><div><Dialog.Title className="text-xl font-black">Name this checkpoint</Dialog.Title><Dialog.Description className="muted mt-2 text-sm">It points to the current accepted cloud state.</Dialog.Description></div><Dialog.Close className="rounded-lg p-2 hover:bg-white/5"><X size={18}/></Dialog.Close></div><form onSubmit={create} className="mt-5"><label className="label" htmlFor="checkpointName">Checkpoint name</label><input autoFocus required minLength={2} maxLength={80} className="input" id="checkpointName" value={name} onChange={event=>setName(event.target.value)} placeholder="Before pricing pivot"/><button className="btn btn-primary mt-4 w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={16}/>:<Plus size={16}/>}Create checkpoint</button></form></Dialog.Content></Dialog.Portal></Dialog.Root></div><div className="mt-4 space-y-2">{checkpoints.map(checkpoint=><div className="surface-soft p-3" key={checkpoint.id}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-bold">{checkpoint.name}</div><div className="faint mt-1 text-xs">Sequence {checkpoint.eventSequence} · {checkpoint.automatic?"automatic":"named"}</div></div><span className="pill">v{checkpoint.stateVersion}</span></div><button className="mt-3 flex items-center gap-1.5 text-xs font-bold text-emerald-300" disabled={pending} onClick={()=>fork(checkpoint.id)}><GitFork size={13}/>Fork from here</button></div>)}</div></section>{error&&<div role="alert" className="rounded-xl border border-red-400/25 bg-red-400/8 p-3 text-sm text-red-200">{error}</div>}<div className="surface-soft p-4"><History className="text-sky-300" size={18}/><p className="muted mt-3 text-xs leading-5">Undo never deletes an event. A fork starts a new run from a checkpoint and records the parent relationship.</p></div></aside></div>;
}
