"use client";
import { LoaderCircle, Play } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

export function RunSetupForm({ scenarioSlug, scenarioVersion, authenticated, playable = true }: { scenarioSlug: string; scenarioVersion: string; authenticated: boolean; playable?: boolean }) {
  const router = useRouter(); const [pending,setPending]=useState(false); const [error,setError]=useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!authenticated) { router.push("/start"); return; }
    setPending(true);setError("");const data=new FormData(event.currentTarget);
    const v10=scenarioVersion.startsWith("3.");
    const response=await fetch("/api/v1/runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarioSlug,setup:v10?{companyName:data.get("companyName"),founderProfileId:data.get("founderProfileId")}:{companyName:data.get("companyName"),founderArchetype:data.get("founderArchetype"),difficulty:data.get("difficulty"),personalRunway:data.get("personalRunway")}})});
    const body=await response.json();setPending(false);if(!response.ok){setError(body.error??"Could not start the run.");return;}router.push(`/runs/${body.run.id}`);router.refresh();
  }
  const v10=scenarioVersion.startsWith("3.");
  return <form onSubmit={submit} className="surface p-5 sm:p-6"><h2 className="text-xl font-black">Configure your founder</h2><p className="muted mt-2 text-sm">The world model and challenge profile are fixed by this immutable scenario version.</p><div className="mt-5 space-y-4"><div><label className="label" htmlFor="companyName">Startup name</label><input className="input" required minLength={2} maxLength={42} id="companyName" name="companyName" defaultValue="Tiny Orbit"/></div>{v10?<div><label className="label" htmlFor="founderProfileId">Founder profile</label><select className="input" id="founderProfileId" name="founderProfileId" defaultValue="technical_builder"><option value="technical_builder">Technical builder</option><option value="commercial_hunter">Commercial hunter</option><option value="domain_insider">Domain insider</option><option value="community_operator">Community operator</option></select></div>:<><div><label className="label" htmlFor="founderArchetype">Founder archetype</label><select className="input" id="founderArchetype" name="founderArchetype" defaultValue="builder"><option value="builder">Technical builder</option><option value="seller">Sales-led founder</option><option value="expert">Domain expert</option><option value="community">Community-led maker</option></select></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label" htmlFor="difficulty">Difficulty</label><select className="input" id="difficulty" name="difficulty" defaultValue="realistic"><option value="guided">Guided</option><option value="realistic">Realistic</option><option value="brutal">Brutal</option></select></div><div><label className="label" htmlFor="personalRunway">Personal runway</label><select className="input" id="personalRunway" name="personalRunway" defaultValue="standard"><option value="pressure">Pressure</option><option value="standard">Standard</option><option value="stable">Stable buffer</option></select></div></div></>}</div>{!playable&&<p role="status" className="mt-4 text-sm text-amber-200">This calibration build is disabled in production until the release gates pass.</p>}{error&&<p role="alert" className="mt-4 text-sm text-red-300">{error}</p>}<button className="btn btn-primary mt-6 w-full" disabled={pending||!playable}>{pending?<LoaderCircle className="animate-spin" size={16}/>:<Play size={16}/>} {!playable?"Calibration gate active":authenticated?"Start scenario":"Create a session to play"}</button></form>;
}
