"use client";
import * as Dialog from "@radix-ui/react-dialog";
import { Check, Copy, KeyRound, LogOut, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function SettingsActions(){const router=useRouter();const [code,setCode]=useState("");const [error,setError]=useState("");const [copied,setCopied]=useState(false);const [pending,setPending]=useState(false);
  async function rotate(){setPending(true);setError("");const response=await fetch("/api/v1/session/recovery/rotate",{method:"POST"});const body=await response.json();setPending(false);if(!response.ok){setError(body.error);return}setCode(body.recoveryCode)}
  async function logout(){setPending(true);await fetch("/api/v1/session/logout",{method:"POST"});router.push("/");router.refresh()}
  return <div className="space-y-3"><Dialog.Root open={Boolean(code)} onOpenChange={open=>!open&&setCode("")}><button className="btn btn-secondary w-full sm:w-auto" disabled={pending} onClick={rotate}><KeyRound size={16}/>Rotate recovery code</button><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm"/><Dialog.Content className="surface fixed left-1/2 top-1/2 z-50 w-[min(92vw,520px)] -translate-x-1/2 -translate-y-1/2 p-6"><div className="flex justify-between"><div><Dialog.Title className="text-xl font-black">Save the replacement code</Dialog.Title><Dialog.Description className="muted mt-2 text-sm">The previous code is now invalid.</Dialog.Description></div><Dialog.Close className="p-2"><X size={18}/></Dialog.Close></div><div className="mt-5 flex items-center gap-2 rounded-xl border border-amber-300/25 bg-amber-300/7 p-3 font-mono text-xs"><code className="min-w-0 flex-1 break-all">{code}</code><button className="btn btn-secondary !min-h-9 !px-3" onClick={async()=>{await navigator.clipboard.writeText(code);setCopied(true)}}>{copied?<Check size={15}/>:<Copy size={15}/>}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root><button className="btn btn-danger w-full sm:ml-2 sm:w-auto" disabled={pending} onClick={logout}><LogOut size={16}/>Sign out this session</button>{error&&<p className="text-sm text-red-300" role="alert">{error}</p>}</div>}
