import { notFound } from "next/navigation";
import { CheckCircle2 } from "lucide-react";
import { PublicNav } from "@/components/public-nav";
import { RunSetupForm } from "@/components/run-setup-form";
import { getScenario } from "@/content/scenarios";
import { currentUser } from "@/server/auth/session";

export default async function ScenarioDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const {slug}=await params;const scenario=getScenario(slug);if(!scenario||scenario.hidden)notFound();const user=await currentUser();
  return <><PublicNav/><main className="container-page grid gap-10 py-14 lg:grid-cols-[1.1fr_.75fr]"><section><div className="flex flex-wrap gap-2"><span className="pill pill-good">{scenario.difficultyLabel}</span><span className="pill">{scenario.estimatedMinutes} minutes</span><span className="pill">v{scenario.version}</span></div><h1 className="title-balance mt-5 text-4xl font-black tracking-[-.05em] sm:text-6xl">{scenario.title}</h1><p className="mt-4 text-xl font-semibold text-slate-300">{scenario.subtitle}</p><p className="muted mt-6 max-w-3xl text-base leading-8">{scenario.description}</p><div className="mt-9 grid gap-4 sm:grid-cols-2"><div className="surface-soft p-4"><div className="eyebrow">Starting market</div><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between"><dt className="muted">Vertical</dt><dd>{scenario.vertical}</dd></div><div className="flex justify-between"><dt className="muted">Architecture</dt><dd>{scenario.architecture}</dd></div><div className="flex justify-between"><dt className="muted">GTM thesis</dt><dd>{scenario.strategy}</dd></div><div className="flex justify-between"><dt className="muted">Company cash</dt><dd>${scenario.initial.companyCash}</dd></div></dl></div><div className="surface-soft p-4"><div className="eyebrow">Learning objectives</div><ul className="mt-3 space-y-2">{scenario.learningObjectives.map(item=><li className="flex gap-2 text-sm" key={item}><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-300" size={16}/><span>{item}</span></li>)}</ul></div></div><div className="mt-8"><h2 className="text-xl font-black">Initial decision pressure</h2><div className="mt-4 grid gap-3">{scenario.problems.map(problem=><div className="surface-soft flex items-start justify-between gap-4 p-4" key={problem.key}><div><h3 className="font-bold">{problem.title}</h3><p className="muted mt-1 text-sm leading-6">{problem.summary}</p></div><span className={`pill ${problem.severity>=4?'pill-bad':'pill-warn'}`}>{problem.severity}/5</span></div>)}</div></div></section><aside><RunSetupForm scenarioSlug={scenario.slug} authenticated={Boolean(user)}/></aside></main></>;
}
